export const FIELD_TYPES = {
  DROPDOWN: 'DROPDOWN',
  GROUP: 'GROUP',
  TEXT: 'TEXT',
  URL: 'URL',
};

export const FIELDS = {
  owner: {
    name: 'entry.1232059513',
    type: FIELD_TYPES.DROPDOWN,
    required: true,
    options: ['Osman Dawe', 'Norton Akenga', 'Irene kamene', 'Oliver Kiprono', 'Bernice Atieno', 'Ryan Omondi', 'Sarah Wangah', 'Rebeccah Ndungi', 'Thomas Oduol', 'Leonard Terer', 'Isaac Kenga', 'John kang\'ethe', 'Douglas Mwarumba', 'Morris Maluni', 'Ezra Kigen', 'Isaac Mutunga', 'Kevin Kemboi', 'Dennis Kibet', 'Andrew Kamau', 'Abraham Kemboi', 'Joseph Mwau', 'Wendy Viola', 'Grace Jemeli', 'Rose Makau', 'Jonathan Kombich', 'Elizabeth Onyango', 'Ruth Gichina', 'Kelvin Mwangi'],
    displayName: 'Owner',
    category: '',
    parent: '',
  },
  icnumber: {
    name: 'entry.1277951088',
    type: FIELD_TYPES.TEXT,
    required: true,
    options: [],
    displayName: 'IC Number',
    category: '',
    parent: 'IC Number',
    placeholder: 'IC Number',
  },
  project: {
    name: 'entry.1129632657',
    type: FIELD_TYPES.DROPDOWN,
    required: true,
    options: ['High Priority', 'ActiveJobsCheck', 'Jira Ticket', 'Unhealthy Project', 'User feedback'],
    displayName: 'Project',
    category: '',
    parent: '',
  },
  ticketType: {
    name: 'entry.87220949',
    type: FIELD_TYPES.DROPDOWN,
    required: true,
    options: ['Mill Valley Ticket', 'New Ticket', 'N/A'],
    displayName: 'Ticket Type',
    category: 'JIRA',
    parent: '',
  },
  url: {
    name: 'entry.1513688965',
    type: FIELD_TYPES.URL,
    required: true,
    options: [],
    displayName: 'Integrations queue Url',
    category: 'UNHEALTHY',
    parent: 'Pre-Crawl',
    unhealthy: 'Main Url on IC',
    placeholder: 'url'
  },
  crawlType: {
    name: 'entry.1448858690',
    type: FIELD_TYPES.DROPDOWN,
    required: true,
    options: ['TARAKAN', 'JCRAWLER', 'XML FEED', 'MASTER FEED', 'CANNOT-CRAWL'],
    displayName: 'Crawl Type',
    category: '',
    parent: 'Pre-Crawl',
  },
  comment: {
    name: 'entry.564759693',
    type: FIELD_TYPES.TEXT,
    required: false,
    options: [],
    displayName: 'Give a brief Comment if it is Cannot-Crawl',
    category: 'CANNOT CRAWL',
    parent: 'Pre-Crawl',
    placeholder: 'comment',
  },
  checkemployerexist: {
    name: 'entry.927175183',
    type: FIELD_TYPES.GROUP,
    required: true,
    options: ['Yes', 'No', 'N/A'],
    displayName: 'Checked if employer exist on Glassdoor?',
    category: '',
    parent: 'Employer Check',
  },
  checkmoreemployers: {
    name: 'entry.1426142585',
    type: FIELD_TYPES.GROUP,
    required: true,
    options: ['Yes', 'No', 'N/A'],
    displayName: 'Checked to see if there\'s more than one employer involved?',
    category: '',
    parent: 'Employer Check',
  },
  checkexistingic: {
    name: 'entry.981306830',
    type: FIELD_TYPES.GROUP,
    required: true,
    options: ['Yes', 'No', 'N/A'],
    displayName: 'Check if there is an existing IC?',
    category: '',
    parent: 'Employer Check',
  },
  xpaths: {
    name: 'entry.2127786391',
    type: FIELD_TYPES.GROUP,
    required: false,
    options: ['Yes', 'No', 'N/A'],
    displayName: 'Included 4 basic Xpaths?',
    category: '',
    parent: 'Custom Crawl Rules',
  },
  pprs: {
    name: 'entry.1695002413',
    type: FIELD_TYPES.GROUP,
    required: false,
    options: ['Yes', 'No', 'N/A'],
    displayName: 'Included all necessary PPRs?',
    category: '',
    parent: 'Custom Crawl Rules',
  },
  jobCount: {
    name: 'entry.1302079706',
    type: FIELD_TYPES.GROUP,
    required: false,
    options: ['Yes', 'No', 'N/A'],
    displayName: 'Filled the Expected Job Count?',
    category: '',
    parent: 'Custom Crawl Rules',
  },
  IDFromSource: {
    name: 'entry.1663521334',
    type: FIELD_TYPES.GROUP,
    required: false,
    options: ['Yes', 'No', 'N/A'],
    displayName: 'Captured IDFromSource and jobListingEmail?',
    category: '',
    parent: 'Custom Crawl Rules',
  },
  unhealthyicstatus: {
    name: 'entry.950348769',
    type: FIELD_TYPES.GROUP,
    required: false,
    options: ['Done', 'Pending', 'N/A'],
    displayName: 'What is the final status of the IC?',
    category: 'UNHEALTHY',
    parent: '',
  },
  icstatus: {
    name: 'entry.652043842',
    type: FIELD_TYPES.GROUP,
    required: false,
    options: ['Enabled', 'Disabled'],
    displayName: 'What is the final Status of the IC?',
    category: '',
    parent: 'IC Number',
  },
  existingic: {
    name: 'entry.1008621477',
    type: FIELD_TYPES.GROUP,
    required: false,
    options: ['Yes', 'No'],
    displayName: 'Existing IC',
    category: '',
    parent: '',
  },
};
